version: '2'
services:
  redis-node-0:
    container_name: redis-node-0
    image: docker.io/bitnami/redis-cluster:${REDIS_VERSION:-6.2}
    volumes:
      - ./.data/redis-node-0:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-bitnami}
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    restart: always

  redis-node-1:
    container_name: redis-node-1
    image: docker.io/bitnami/redis-cluster:${REDIS_VERSION:-6.2}
    volumes:
      - ./.data/redis-node-1:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-bitnami}
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    restart: always

  redis-node-2:
    container_name: redis-node-2
    image: docker.io/bitnami/redis-cluster:${REDIS_VERSION:-6.2}
    volumes:
      - ./.data/redis-node-2:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-bitnami}
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    restart: always

  redis-node-3:
    container_name: redis-node-3
    image: docker.io/bitnami/redis-cluster:${REDIS_VERSION:-6.2}
    volumes:
      - ./.data/redis-node-3:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-bitnami}
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    restart: always

  redis-node-4:
    container_name: redis-node-4
    image: docker.io/bitnami/redis-cluster:${REDIS_VERSION:-6.2}
    volumes:
      - ./.data/redis-node-4:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-bitnami}
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    restart: always

  redis-node-5:
    container_name: redis-node-5
    image: docker.io/bitnami/redis-cluster:${REDIS_VERSION:-6.2}
    volumes:
      - ./.data/redis-node-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-bitnami}
      REDISCLI_AUTH: ${REDIS_PASSWORD:-bitnami}
      REDIS_CLUSTER_REPLICAS: 1
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      REDIS_CLUSTER_CREATOR: "yes"
    restart: always

networks:
  default:
    external:
      name: dev-network
